name: laoma_tingshu
description: LaoMa Pro Audio Book Final
publish_to: 'none'
version: 2.5.0+8
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  html: ^0.15.3
  webview_flutter: ^4.2.2
  shared_preferences: ^2.1.0
flutter:
  uses-material-design: true
