name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter create . --platforms android --project-name laoma_tingshu
          # 【核心补丁】强行插入联网权限
          sed -i '/<application/i <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          # 【核心补丁】强制允许访问 http 网站（解决搜不到的核心）
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          mkdir -p lib
          find . -maxdepth 2 -name "main.dart" -exec cp {} lib/main.dart \;
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LaoMaApp
          path: build/app/outputs/flutter-apk/app-release.apk
